name: ChainDB

on:
  push:
    branches:
      - main
      - release-*
    pull_request:
      branches:
        - main
        - release-*
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [18.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: Use node version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install deps
        run: yarn install
      - name: Build Project
        run: yarn build
